#index:
#    path: /
#    controller: App\Controller\DefaultController::index
GetLuckyNumber:
  path:       /lucky/number/{max}
  controller: App\Controller\LuckyController::number
  methods:    GET

GetTariff:
  path:       /tariff/{tariffId}
  controller: App\Controller\TariffController::getTariff
  methods:    GET
  requirements:
    tariffId: '\d+'

CreateTariff:
  path:       /tariff
  controller: App\Controller\TariffController::create
  methods:    POST

UpdateTariff:
  path:       /tariff/{tariffId}
  controller: App\Controller\TariffController::update
  methods:    PATCH
  requirements:
    tariffId: '\d+'

DeleteTariff:
  path:       /tariff/{tariffId}
  controller: App\Controller\TariffController::delete
  methods:    DELETE
  requirements:
    tariffId: '\d+'

GetFlights:
  path:       /flights
  controller: App\Controller\FlightController::getAll
  methods:    GET

GetFlight:
  path:       /flight/{flightId}
  controller: App\Controller\FlightController::getFlight
  methods:    GET
  requirements:
    flightId: '\d+'

CreateFlight:
  path:       /flight
  controller: App\Controller\FlightController::create
  methods:    POST

UpdateFlight:
  path:       /flight/{flightId}
  controller: App\Controller\FlightController::update
  methods:    PATCH
  requirements:
    flightId: '\d+'

DeleteFlight:
  path:       /flight/{flightId}
  controller: App\Controller\FlightController::delete
  methods:    DELETE
  requirements:
    flightId: '\d+'

GetFlightTariffs:
  path:       /flight/{flightId}/tariffs
  controller: App\Controller\FlightController::getFlightTariffs
  methods:    GET
  requirements:
    flightId: '\d+'

GetToken:
  path:       /auth
  controller: App\Controller\AuthController::getToken
  methods:    POST